name: personal-finance-advisor

services:
  mysql:
    image: mysql:8.4.2
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: personal_finance_advisor

    volumes:
      - mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

    networks:
      - backend

  node:
    build: .
    container_name: node
    ports:
      - '127.0.0.1:5500:5500'

    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_DATABASE: personal_finance_advisor
      DB_PASSWORD: password
      JWT_SECRET_KEY: secret
      PORT: 5500

    volumes:
      - npm-cache:/root/.npm
      - ./dist:/app/src

    networks:
      - backend

volumes:
  npm-cache:
  mysql-data:

networks:
  backend:
